[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pycumin"
version = "0.1.0.dev4"
description = "Containment-based Unordered Mapping Index for Nanopore"
authors = [
    { name="Sayan Goswami", email="sgoswami@smcm.edu" }
]

[tool.scikit-build.cmake]
build-type = "Release"

[project.scripts]
pycumin = "pycumin.cumin:main"
