[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycumin"
version = "0.1.0.dev1"
description = "Containment-based Unordered Mapping Index for Nanopore"
authors = [
    { name="Sayan Goswami", email="sgoswami@smcm.edu" }
]

[tool.setuptools.packages.find]
where = ["src"]